AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Serverless stack for AgePrediction (S3 + Lambda).

Parameters:
  BucketPrefix:
    Type: String
    Default: agepred
  FunctionMemorySize:
    Type: Number
    Default: 2048
  FunctionTimeout:
    Type: Number
    Default: 60
  PresignExpireSeconds:
    Type: Number
    Default: 600
  ResultUrlExpireSeconds:
    Type: Number
    Default: 3600

Resources:
  UploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${BucketPrefix}-uploads-${AWS::AccountId}-${AWS::Region}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  ResultsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${BucketPrefix}-results-${AWS::AccountId}-${AWS::Region}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  PredictFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: predict_age
      PackageType: Image
      MemorySize: !Ref FunctionMemorySize
      Timeout: !Ref FunctionTimeout
      Environment:
        Variables:
          S3_UPLOAD_BUCKET: !Ref UploadBucket
          S3_RESULTS_BUCKET: !Ref ResultsBucket
          S3_REGION: !Ref AWS::Region
          S3_PRESIGN_EXPIRES_SECONDS: !Ref PresignExpireSeconds
          S3_RESULT_URL_EXPIRES_SECONDS: !Ref ResultUrlExpireSeconds
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref UploadBucket
        - S3CrudPolicy:
            BucketName: !Ref ResultsBucket
    Metadata:
      Dockerfile: Dockerfile.lambda
      DockerContext: .
      DockerTag: latest


Outputs:
  UploadBucketName:
    Value: !Ref UploadBucket
  ResultsBucketName:
    Value: !Ref ResultsBucket
