AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Serverless stack for AgePrediction (S3 + Lambda).

Parameters:
  BucketPrefix:
    Type: String
    Default: agepred
  FunctionMemorySize:
    Type: Number
    Default: 2048
  FunctionTimeout:
    Type: Number
    Default: 60
  PresignExpireSeconds:
    Type: Number
    Default: 600
  ResultUrlExpireSeconds:
    Type: Number
    Default: 3600
  ImageUri:
    Type: String
    Description: ECR image URI (repo:tag or repo@digest) for PredictFunction.

Resources:
  UploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${BucketPrefix}-uploads-${AWS::AccountId}-${AWS::Region}"
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - "*"
            AllowedMethods:
              - PUT
              - GET
              - HEAD
            AllowedHeaders:
              - "*"
            MaxAge: 3000
      LifecycleConfiguration:
        Rules:
          - Id: ExpireUploadsAfterOneDay
            Status: Enabled
            ExpirationInDays: 1
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  ResultsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${BucketPrefix}-results-${AWS::AccountId}-${AWS::Region}"
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - "*"
            AllowedMethods:
              - GET
              - HEAD
            AllowedHeaders:
              - "*"
            MaxAge: 3000
      LifecycleConfiguration:
        Rules:
          - Id: ExpireResultsAfterOneDay
            Status: Enabled
            ExpirationInDays: 1
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${BucketPrefix}-frontend-${AWS::AccountId}-${AWS::Region}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  FrontendOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub "${BucketPrefix}-frontend-oac-${AWS::Region}"
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  FrontendDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        Aliases:
          - facepredictionservice.com
          - www.facepredictionservice.com
        ViewerCertificate:
          AcmCertificateArn: arn:aws:acm:us-east-1:555813168261:certificate/ba4acde9-face-4a53-8b5e-d13170320c85
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        Origins:
          - Id: FrontendS3Origin
            DomainName: !GetAtt FrontendBucket.RegionalDomainName
            S3OriginConfig: {}
            OriginAccessControlId: !GetAtt FrontendOriginAccessControl.Id
        DefaultCacheBehavior:
          TargetOriginId: FrontendS3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
          Compress: true
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none

  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowCloudFrontRead
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action:
              - "s3:GetObject"
            Resource: !Sub "${FrontendBucket.Arn}/*"
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${FrontendDistribution}"

  PredictFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: predict_age
      PackageType: Image
      ImageUri: !Ref ImageUri
      MemorySize: !Ref FunctionMemorySize
      Timeout: !Ref FunctionTimeout
      Environment:
        Variables:
          S3_UPLOAD_BUCKET: !Ref UploadBucket
          S3_RESULTS_BUCKET: !Ref ResultsBucket
          S3_REGION: !Ref AWS::Region
          S3_PRESIGN_EXPIRES_SECONDS: !Ref PresignExpireSeconds
          S3_RESULT_URL_EXPIRES_SECONDS: !Ref ResultUrlExpireSeconds
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref UploadBucket
        - S3CrudPolicy:
            BucketName: !Ref ResultsBucket
      Events:
        ApiRoot:
          Type: Api
          Properties:
            Path: /
            Method: ANY
            RestApiId: !Ref AgePredApi
        ApiProxy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref AgePredApi

  AgePredApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type'"
        AllowOrigin: "'https://facepredictionservice.com,https://www.facepredictionservice.com'"

Outputs:
  UploadBucketName:
    Value: !Ref UploadBucket
  ResultsBucketName:
    Value: !Ref ResultsBucket
  ApiBaseUrl:
    Value: !Sub "https://${AgePredApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
  FrontendBucketName:
    Value: !Ref FrontendBucket
  CloudFrontUrl:
    Value: !Sub "https://${FrontendDistribution.DomainName}"
  CloudFrontDistributionId:
    Value: !Ref FrontendDistribution
